# Generated by Django 2.0 on 2018-04-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelfindernyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='suites',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tennis_court',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='hotel',
            name='wheelchair_access',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='hotel',
            name='wifi',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
