# Generated by Django 2.0 on 2018-04-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelfindernyc', '0002_auto_20180414_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='pool',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='hotel',
            name='public_wifi',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='hotel',
            name='restaurant',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rooftop_bar',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rooftop_terrace',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
