# Generated by Django 2.0 on 2018-04-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelfindernyc', '0004_auto_20180416_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
