# Generated by Django 2.0 on 2018-04-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelfindernyc', '0005_hotel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='n1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='n10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='n2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='n3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='n4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='n5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='n6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='n7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='n8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='n9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='p1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='p10',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='p2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='p3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='p4',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='p5',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='p6',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='p7',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='p8',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='p9',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
