# Generated by Django 2.0 on 2018-04-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelfindernyc', '0006_auto_20180420_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
